// i18n/build-locale.js
// Merges hand-authored translation maps (i18n/de.map.json, i18n/en.map.json)
// against the authoritative key list in strings.tr.json and writes the runtime
// dictionaries public/locales/{de,en}.json. Only keys with a non-empty
// translation are emitted — the server falls back to the Turkish source for
// anything missing, so partial coverage degrades gracefully.
//
// It also reports coverage and flags any map keys that don't exist in the
// source (typos / stale strings) so translations never silently fail to apply.
const fs = require('fs');
const path = require('path');

const { normalize } = require('./core');

const srcKeys = Object.keys(JSON.parse(
  fs.readFileSync(path.join(__dirname, 'strings.tr.json'), 'utf8')));
// Match on the NORMALIZED form so translations apply even when the source
// string carries stray C1 bytes that translators rendered as plain spaces.
const srcNorm = new Set(srcKeys.map(normalize));

function build(lang) {
  // Merge every part file: <lang>.map.json and <lang>.map.<n>.json
  const re = new RegExp(`^${lang}\\.map(\\.[^.]+)?\\.json$`);
  const parts = fs.readdirSync(__dirname).filter((f) => re.test(f)).sort();
  let map = {};
  for (const p of parts) {
    Object.assign(map, JSON.parse(fs.readFileSync(path.join(__dirname, p), 'utf8')));
  }

  // Runtime dictionary is keyed by the NORMALIZED source string; render.js
  // looks up normalize(textNode) against it.
  const out = {};
  for (const [k, v] of Object.entries(map)) {
    if (typeof v !== 'string' || v.trim() === '') continue;
    const nk = normalize(k);
    if (srcNorm.has(nk)) out[nk] = v;
  }
  // Merge UI strings that are generated by client JS (not present in the static
  // HTML source), e.g. loading/error messages and button labels. These are
  // included unconditionally — they have no source page to validate against.
  const uiFile = path.join(__dirname, `${lang}.ui.json`);
  if (fs.existsSync(uiFile)) {
    const ui = JSON.parse(fs.readFileSync(uiFile, 'utf8'));
    for (const [k, v] of Object.entries(ui)) {
      if (typeof v === 'string' && v.trim() !== '') out[normalize(k)] = v;
    }
  }

  const covered = Object.keys(out).length;
  // Flag stale/typo'd keys present in the map but not in the source.
  const stale = Object.keys(map).filter((k) => !srcNorm.has(normalize(k)));

  const outFile = path.join(__dirname, '..', 'public', 'locales', `${lang}.json`);
  fs.writeFileSync(outFile, JSON.stringify(out, null, 2), 'utf8');
  const pct = ((covered / srcKeys.length) * 100).toFixed(1);
  console.log(`[${lang}] ${covered}/${srcKeys.length} (${pct}%) translated -> public/locales/${lang}.json`);
  if (stale.length) {
    console.log(`[${lang}] WARNING: ${stale.length} map keys not found in source (first 10):`);
    stale.slice(0, 10).forEach((k) => console.log('   • ' + JSON.stringify(k)));
  }
}

build('de');
build('en');
